export type ColorVariables =
  | 'primary.main'
  | 'primary.light'
  | 'secondary.main'
  | 'secondary.light'
  | 'error.main'
  | 'text.main'
  | 'text.light'
  | 'white.main'
  | 'orange.main'
  | 'orange.light'
